# Generated by Django 3.2.3 on 2021-05-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('pending execution', 'Ожидает выполнения'), ('completed', 'Выполнена'), ('in progress', 'В процессе выполнения')], default='pending execution', max_length=20),
        ),
    ]
