# Generated by Django 3.2.3 on 2021-05-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('high', 'Высокий'), ('midle', 'Средний'), ('low', 'Низкий')], default='midle', max_length=10),
        ),
    ]
